### ISSUE TITLE
Ignore duplicated monospace definitions

### ISSUE THREAD

**Issue by ben-eb** [TrySound/postcss-minify-font-values#5]
In Chrome, these definitions are not the same semantically;

```css
code { font-family: monospace, monospace }
code { font-family: monospace }
```

We should probably exclude the `monospace` keyword from deduplication to avoid fonts being rendered at a small size; this happens when only one `monospace` keyword is provided, but not two.
